Repository codestates-seb/seb40_main_007, pull requests merged in 2022-11, with the labels that each got.

#11 test: member controller test
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/codestates/main007/member/MemberController.java
  src/main/java/codestates/main007/member/MockUpAnswerDto.java
  src/main/java/codestates/main007/member/MockUpDto.java
  src/main/resources/static/docs/index.html
  src/test/java/codestates/main007/member/MemberControllerTest.java
Labels: back

#13 chore: 초기 개발환경 세팅
  client/.eslintrc.json
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/prettierrc.json
  client/public/index.html
  client/src/App.js
  client/src/components/Loading.js
  client/src/components/Sample.js
  client/src/index.css
  client/src/index.js
  client/tailwind.config.js
Labels: front

#16 Test/comment controller test
  src/docs/asciidoc/index.adoc
  src/main/java/codestates/main007/comment/CommentController.java
  src/main/java/codestates/main007/comment/CommentMockUpDto.java
  src/test/java/codestates/main007/comment/CommentControllerTest.java
Labels: back

#14 Test/login controller test
  src/docs/asciidoc/index.adoc
  src/main/java/codestates/main007/login/LoginController.java
  src/main/java/codestates/main007/login/LoginMockUpDto.java
  src/main/java/codestates/main007/member/MemberController.java
  src/main/java/codestates/main007/member/MockUpDto.java
  src/main/resources/static/docs/index.html
  src/test/java/codestates/main007/login/LoginControllerTest.java
  src/test/java/codestates/main007/member/MemberControllerTest.java
Labels: back

#21 Test: boardControllerTest Documentation
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/codestates/main007/board/Board.java
  src/main/java/codestates/main007/board/BoardController.java
  src/main/java/codestates/main007/board/BoardMockUpDto.java
  src/main/java/codestates/main007/member/MockUpDto.java
  src/main/java/codestates/main007/tag/Tag.java
  src/main/java/codestates/main007/tag/TagDto.java
  src/test/java/codestates/main007/board/BoardControllerRestDocsTest.java
Labels: back

#23 Test/asciidocs
  src/main/java/codestates/main007/comment/CommentController.java
  src/main/java/codestates/main007/login/LoginController.java
  src/main/java/codestates/main007/member/MemberController.java
  src/test/java/codestates/main007/comment/CommentControllerTest.java
  src/test/java/codestates/main007/login/LoginControllerTest.java
  src/test/java/codestates/main007/member/MemberControllerTest.java
Labels: back

#25 Style/button header star infowindow
  client/.eslintrc.json
  client/public/images/bluelogo.png
  client/public/images/food.png
  client/src/components/Header.js
  client/src/components/InfoWindow.js
  client/src/components/Sample.js
  client/src/components/StarRating.js
  client/src/components/StarScore.js
  client/src/index.css
Labels: style, front

#24 Test/main controller test
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/codestates/main007/board/Board.java
  src/main/java/codestates/main007/board/BoardController.java
  src/main/java/codestates/main007/board/BoardMockUpDto.java
  src/main/java/codestates/main007/comment/CommentController.java
  src/main/java/codestates/main007/comment/CommentMockUpDto.java
  src/main/java/codestates/main007/login/LoginController.java
  src/main/java/codestates/main007/login/LoginMockUpDto.java
  src/main/java/codestates/main007/member/MemberController.java
  src/main/java/codestates/main007/member/MockUpAnswerDto.java
  src/main/java/codestates/main007/member/MockUpDto.java
  src/main/java/codestates/main007/security/JwtAuthenticationFilter.java
  src/main/java/codestates/main007/security/JwtTokenizer.java
  src/main/java/codestates/main007/security/LoginDto.java
  src/main/java/codestates/main007/security/MemberAuthenticationEntryPoint.java
  src/main/java/codestates/main007/security/SecurityConfig.java
  src/main/java/codestates/main007/security/jwtVerificationFilter.java
  src/main/java/codestates/main007/station/StationController.java
  src/main/java/codestates/main007/tag/Tag.java
  src/main/java/codestates/main007/tag/TagDto.java
  src/main/resources/application.yml
  src/main/resources/static/docs/index.html
  src/test/java/codestates/main007/Main007ApplicationTests.java
  src/test/java/codestates/main007/board/BoardControllerRestDocsTest.java
  src/test/java/codestates/main007/comment/CommentControllerTest.java
  src/test/java/codestates/main007/login/LoginControllerTest.java
  src/test/java/codestates/main007/member/MemberControllerTest.java
Labels: back

#29 [#27] style: 인포윈도우 컴포넌트 제작
  client/src/components/InfoWindow.js
  client/src/components/Sample.js
Labels: style, front

#30 Style/tag editprofile notfound
  client/public/favicon.ico
  client/public/images/notfound_icon_sb.png
  client/public/images/notfound_icon_w.png
  client/public/images/profile.png
  client/public/index.html
  client/src/components/editfrofile/EditBtn.js
  client/src/components/editfrofile/EditProfileImg.js
  client/src/components/mycomment/MyCommentList.js
  client/src/components/notfound/NotFoundSb.js
  client/src/components/notfound/NotFoundW.js
  client/src/components/tag/ListTag.js
  client/src/components/tag/Tag.js
  client/src/components/tag/TagBtn.js
Labels: style, front

#31 Style/train station modal
  client/public/images/logo.png
  client/public/images/광명역.png
  client/public/images/구포역.png
  client/public/images/김천구미역.png
  client/public/images/대전역.png
  client/public/images/동대구역.png
  client/public/images/밀양역.png
  client/public/images/부산역.png
  client/public/images/서울역.png
  client/public/images/수원역.png
  client/public/images/신경주역.png
  client/public/images/영등포역.png
  client/public/images/오송역.png
  client/public/images/울산역.png
  client/public/images/천안아산역.png
  client/public/images/행신역.png
  client/src/Routes/samplePage.js
  client/src/components/AlertModal.js
  client/src/components/TrainStationModal.js
Labels: style, front

#37 Feat/comments
  build.gradle
  src/main/java/codestates/main007/comments/Comment.java
  src/main/java/codestates/main007/comments/CommentController.java
  src/main/java/codestates/main007/comments/CommentDto.java
  src/main/java/codestates/main007/comments/CommentMapper.java
  src/main/java/codestates/main007/comments/CommentRepository.java
  src/main/java/codestates/main007/comments/CommentService.java
Labels: back, feat

#34 Feat/boards
  build.gradle
  src/main/java/codestates/main007/board/Board.java
  src/main/java/codestates/main007/board/BoardController.java
  src/main/java/codestates/main007/board/BoardDto.java
  src/main/java/codestates/main007/board/BoardMapper.java
  src/main/java/codestates/main007/board/BoardRepository.java
  src/main/java/codestates/main007/board/BoardService.java
  src/test/java/codestates/main007/Main007ApplicationTest.java
Labels: back, feat

#39 Feat/member
  src/main/java/codestates/main007/dto/MultiResponseDto.java
  src/main/java/codestates/main007/member/Member.java
  src/main/java/codestates/main007/member/MemberController.java
  src/main/java/codestates/main007/member/MemberDto.java
  src/main/java/codestates/main007/member/MemberMapper.java
  src/main/java/codestates/main007/member/MemberRepository.java
  src/main/java/codestates/main007/member/MemberService.java
Labels: back, feat

#40 Feat: be-exception추가
  src/main/java/codestates/main007/exception/BusinessLogicException.java
  src/main/java/codestates/main007/exception/ExceptionCode.java
Labels: back, feat

#44 Feat/board member
  src/main/java/codestates/main007/board/Board.java
  src/main/java/codestates/main007/board/BoardController.java
  src/main/java/codestates/main007/board/BoardDto.java
  src/main/java/codestates/main007/board/BoardMapper.java
  src/main/java/codestates/main007/board/BoardRepository.java
  src/main/java/codestates/main007/board/BoardService.java
  src/main/java/codestates/main007/comments/Comment.java
  src/main/java/codestates/main007/comments/CommentController.java
  src/main/java/codestates/main007/comments/CommentMapper.java
  src/main/java/codestates/main007/comments/CommentRepository.java
  src/main/java/codestates/main007/comments/CommentService.java
  src/main/java/codestates/main007/member/Member.java
  src/main/java/codestates/main007/member/MemberController.java
  src/main/java/codestates/main007/member/MemberDto.java
  src/main/java/codestates/main007/member/MemberMapper.java
  src/main/java/codestates/main007/member/MemberService.java
  src/main/java/codestates/main007/member/query/MemberScore.java
  src/main/java/codestates/main007/member/query/MemberStation.java
  src/main/resources/application.yml
Labels: back, feat

#46 Feat/service
  build.gradle
  src/main/java/codestates/main007/service/EmailService.java
  src/main/java/codestates/main007/service/RandomAvatarService.java
  src/main/java/codestates/main007/service/RandomNamingService.java
  src/main/resources/application.yml
Labels: back, feat

#50 Feat/services
  src/main/java/codestates/main007/Main007Application.java
  src/main/java/codestates/main007/member/Member.java
  src/main/java/codestates/main007/member/MemberController.java
  src/main/java/codestates/main007/member/MemberDto.java
  src/main/java/codestates/main007/member/MemberMapper.java
  src/main/java/codestates/main007/member/MemberRepository.java
  src/main/java/codestates/main007/member/MemberService.java
  src/main/java/codestates/main007/service/EmailService.java
  src/main/java/codestates/main007/service/RandomAvatarService.java
  src/main/java/codestates/main007/service/RandomNamingService.java
  src/main/java/codestates/main007/service/RandomPasswordService.java
  src/main/resources/application.yml
Labels: back, feat

#53 Feat/station
  src/main/java/codestates/main007/board/Board.java
  src/main/java/codestates/main007/board/BoardMapper.java
  src/main/java/codestates/main007/board/BoardService.java
  src/main/java/codestates/main007/member/MemberController.java
  src/main/java/codestates/main007/service/DistanceMeasuringService.java
  src/main/java/codestates/main007/station/Station.java
  src/main/resources/application.yml
Labels: back, feat

#47 Style/alert modal
  client/public/images/close_quote.png
  client/public/images/gradation.png
  client/public/images/kakao.png
  client/public/images/naver.png
  client/public/images/open_quote.png
  client/public/images/기차역도장/광명역.png
  client/public/images/기차역도장/구포역.png
  client/public/images/기차역도장/김천구미역.png
  client/public/images/기차역도장/대전역.png
  client/public/images/기차역도장/동대구역.png
  client/public/images/기차역도장/밀양역.png
  client/public/images/기차역도장/부산역.png
  client/public/images/기차역도장/서울역.png
  client/public/images/기차역도장/수원역.png
  client/public/images/기차역도장/신경주역.png
  client/public/images/기차역도장/영등포역.png
  client/public/images/기차역도장/오송역.png
  client/public/images/기차역도장/울산역.png
  client/public/images/기차역도장/천안아산역.png
  client/public/images/기차역도장/행신역.png
  client/public/images/기차역사진/광명역사진.png
  client/public/images/기차역사진/구포역사진.png
  client/public/images/기차역사진/기차역없음사진.png
  client/public/images/기차역사진/김천구미역사진.png
  client/public/images/기차역사진/대전역사진.png
  client/public/images/기차역사진/동대구역사진.png
  client/public/images/기차역사진/밀양역사진.png
  client/public/images/기차역사진/부산역사진.png
  client/public/images/기차역사진/서울역사진.png
  client/public/images/기차역사진/수원역사진.png
  client/public/images/기차역사진/신경주역사진.png
  client/public/images/기차역사진/영등포역사진.png
  client/public/images/기차역사진/오송역사진.png
  client/public/images/기차역사진/울산역사진.png
  client/public/images/기차역사진/천안아산역사진.png
  client/public/images/기차역사진/행신역사진.png
  client/src/App.js
  client/src/Routes/homePage.js
  client/src/Routes/initialPage.js
  client/src/Routes/loginPage.js
  client/src/Routes/signUpPage.js
  client/src/components/AlertModal.js
  client/src/components/Header.js
  client/src/components/Heart.js
  client/src/components/ImageUpload.js
  client/src/components/MyPageTab.js
  client/src/components/OneLineComment.js
  client/src/components/Sample.js
  client/src/components/TrainStationCard.js
  client/src/components/TrainStationSelect.js
  client/src/components/modals/AlertModal.js
  client/src/components/modals/TrainStationModal.js
  client/src/utils/useForm.js
Labels: style, front

#55 내 정보, 내 정보수정, 비밀번호 수정 디자인 코드 입니다.
  client/src/Routes/EditMyInfoPage.js
  client/src/Routes/EditPasswordPage.js
  client/src/Routes/MyProfilePage.js
  client/src/components/editfrofile/EditProfileImg.js
  client/src/components/editmyinfo/EditBtn.js
  client/src/components/editmyinfo/EditNickname.js
  client/src/components/editmyinfo/EditProfileImg.js
  client/src/components/editpassword/ConfirmPassword.js
  client/src/components/editpassword/EditPasswordInput.js
  client/src/components/mycomment/MyCommentItem.js
  client/src/components/mycomment/MyCommentList.js
  client/src/components/myprofile/infoeditbtn/InfoEditBtn.js
  client/src/components/myprofile/infoeditbtn/InfoEditMenu.js
  client/src/components/myprofile/myinfo/MyInfo.js
  client/src/components/myprofile/mystation/MyStation.js
  client/src/components/myprofile/mystation/MyStationItem.js
  client/tailwind.config.js
Labels: style, front

#57 Feat/pagenation
  src/main/java/codestates/main007/MainController.java
  src/main/java/codestates/main007/board/BoardDto.java
  src/main/java/codestates/main007/board/BoardMapper.java
  src/main/java/codestates/main007/board/BoardRepository.java
  src/main/java/codestates/main007/board/BoardService.java
  src/main/java/codestates/main007/comments/CommentRepository.java
  src/main/java/codestates/main007/dto/PageDto.java
  src/main/java/codestates/main007/dto/PageInfo.java
  src/main/java/codestates/main007/member/MemberController.java
  src/main/java/codestates/main007/member/MemberService.java
  src/main/java/codestates/main007/service/RandomNamingService.java
Labels: back, feat

#60 Style/mainpage detailpage
  client/package-lock.json
  client/package.json
  client/public/images/bluelogo.png
  client/public/images/crap.png
  client/public/images/logo.png
  client/public/images/oyster.png
  client/public/images/quote1.png
  client/public/images/quote2.png
  client/src/Routes/DetailPage.js
  client/src/Routes/MainPage.js
  client/src/atoms/filter.js
  client/src/components/DetailPage/CommentEditor.js
  client/src/components/DetailPage/Comments/Comment.js
  client/src/components/DetailPage/Comments/CommentList.js
  client/src/components/DetailPage/DetailHeader/DetailHeader.js
  client/src/components/DetailPage/DetailHeader/DetailStarScore.js
  client/src/components/DetailPage/DetailImageSlider.js
  client/src/components/DetailPage/DetailMap.js
  client/src/components/DetailPage/NeighborhoodPlace.js
  client/src/components/DetailPage/Review/Dislike.js
  client/src/components/DetailPage/Review/Like.js
  client/src/components/DetailPage/Review/Review.js
  client/src/components/Header.js
  client/src/components/InfoWindow.js
  client/src/components/MainPage/CategoryTab.js
  client/src/components/MainPage/MainHeader.js
  client/src/components/MainPage/MainMap.js
  client/src/components/MainPage/Posts/Post.js
  client/src/components/MainPage/Posts/PostList.js
  client/src/components/MainPage/Posts/PostStarScore.js
  client/src/components/MainPage/RelatedTab.js
  client/src/components/Sample.js
  client/src/components/WriteModal.js
Labels: style, front

#63 Feat/board member
  src/main/java/codestates/main007/MainController.java
  src/main/java/codestates/main007/board/Board.java
  src/main/java/codestates/main007/board/BoardController.java
  src/main/java/codestates/main007/board/BoardDto.java
  src/main/java/codestates/main007/board/BoardMapper.java
  src/main/java/codestates/main007/board/BoardService.java
  src/main/java/codestates/main007/boardMember/BoardMember.java
  src/main/java/codestates/main007/boardMember/BoardMemberRepository.java
  src/main/java/codestates/main007/boardMember/BoardMemberService.java
  src/main/java/codestates/main007/member/Member.java
Labels: back, feat

#65 푸터 제작, 로그아웃 페이지, 로그인 헤더, 모달 수정
  client/public/images/bluelogo.png
  client/public/images/footerlogo.png
  client/public/images/기차역도장/서대구역.png
  client/public/images/기차역도장/포항역.png
  client/public/images/기차역사진/서대구역사진.png
  client/public/images/기차역사진/포항역사진.png
  client/public/images/역이요노선/역이요_노선.png
  client/public/images/역이요노선/역이요_지도.png
  client/public/images/역이요소개/역이요_소개_1.png
  client/public/images/역이요소개/역이요_소개_2.png
  client/public/images/역이요소개/역이요_소개_3.png
  client/src/App.js
  client/src/Routes/homePage.js
  client/src/Routes/loginPage.js
  client/src/Routes/logoutPage.js
  client/src/Routes/signUpPage.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/ImageUpload.js
  client/src/components/LoginHeader.js
  client/src/components/MainPage/MainHeader.js
  client/src/components/TrainStationCard.js
  client/src/components/TrainStationSelect.js
  client/src/components/modals/ProfileModal.js
  client/src/components/modals/TrainStationModal.js
  client/src/components/myprofile/mystation/MyStation.js
Labels: style, front

#68 마이페이지 - 내 역이요, 내 정보 수정, 비밀번호 변경, 내 댓글 페이지 작성
  client/src/App.js
  client/src/Routes/EditMyInfoPage.js
  client/src/Routes/EditPasswordPage.js
  client/src/Routes/MyProfilePage.js
  client/src/Routes/myCommentPage.js
  client/src/Routes/myPages/editMyInfoPage.js
  client/src/Routes/myPages/editPasswordPage.js
  client/src/Routes/myPages/myProfilePage.js
  client/src/components/MyPageTab.js
  client/src/components/editmyinfo/EditNickname.js
  client/src/components/editmyinfo/EditProfileImg.js
  client/src/components/editpassword/ConfirmPassword.js
  client/src/components/editpassword/EditPasswordInput.js
  client/src/components/mycomment/MyCommentItem.js
  client/src/components/mycomment/MyCommentList.js
  client/src/components/myprofile/infoeditbtn/InfoEditBtn.js
  client/src/components/myprofile/infoeditbtn/InfoEditMenu.js
  client/src/components/myprofile/myinfo/MyInfo.js
  client/src/components/myprofile/mystation/MyStation.js
  client/src/components/myprofile/mystation/MyStationItem.js
  client/src/index.css
  client/tailwind.config.js
Labels: style, front, feat

#69 Style/mainpage detailpage
  client/src/Routes/DetailPage.js
  client/src/Routes/EditPasswordPage.js
  client/src/atoms/filter.js
  client/src/atoms/sort.js
  client/src/components/DetailPage/DetailHeader/DetailHeader.js
  client/src/components/DetailPage/NeighborhoodPlace.js
  client/src/components/Header.js
  client/src/components/MainPage/MainHeader.js
  client/src/components/MainPage/MainMap.js
  client/src/components/MainPage/Posts/Post.js
  client/src/components/MainPage/Posts/PostList.js
  client/src/components/MainPage/Posts/SortDropdown.js
  client/src/components/MainPage/RelatedTab.js
  client/src/components/TrainStationSelect.js
  client/src/components/WriteModal.js
Labels: style, front

#70 fix: 충돌 해결
  client/src/App.js
  client/src/components/Header.js
  client/src/components/MainPage/MainHeader.js
Labels: style, front

#71 파일 이름 변경
  client/src/Routes/detailPage.js
  client/src/Routes/editPasswordPage.js
  client/src/Routes/mainPage.js
Labels: fix, front

#73 Feat/board member
  src/main/java/codestates/main007/board/Board.java
  src/main/java/codestates/main007/board/BoardController.java
  src/main/java/codestates/main007/board/BoardDto.java
  src/main/java/codestates/main007/board/BoardMapper.java
  src/main/java/codestates/main007/board/BoardRepository.java
  src/main/java/codestates/main007/board/BoardService.java
  src/main/java/codestates/main007/boardMember/BoardMember.java
  src/main/java/codestates/main007/boardMember/BoardMemberService.java
  src/main/java/codestates/main007/comments/CommentService.java
Labels: back, feat

#76 Style/Feat: 페이지 디자인 및 무한스크롤 기능
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Routes/myCommentPage.js
  client/src/Routes/myLikePostPage.js
  client/src/Routes/myPages/editMyInfoPage.js
  client/src/Routes/myPages/editPasswordPage.js
  client/src/Routes/myPages/myProfilePage.js
  client/src/Routes/myPostPage.js
  client/src/components/MyPageTab.js
  client/src/components/MyPostTab.js
  client/src/components/TestInfinitiScroll.js
  client/src/components/mycomment/MyCommentItem.js
Labels: style, fix, front, feat

#79 Style/loading
  client/public/images/train.png
  client/src/components/Loading.js
  client/src/components/MainPage/Posts/PostList.js
  client/src/components/editmyinfo/EditProfileImg.js
  client/tailwind.config.js
Labels: style, front

#81 Style/footer
  client/public/index.html
  client/src/App.js
  client/src/components/Header.js
  client/src/components/LoginHeader.js
  client/src/components/MainPage/MainMap.js
  client/src/components/OneLineInput.js
  client/src/components/TrainStationSelect.js
  client/src/components/WriteModal.js
  client/src/components/modals/ProfileModal.js
  client/src/components/modals/TrainStationModal.js
Labels: style, front

#75 Feat/board image
  build.gradle
  src/main/java/codestates/main007/board/Board.java
  src/main/java/codestates/main007/board/BoardController.java
  src/main/java/codestates/main007/board/BoardDto.java
  src/main/java/codestates/main007/board/BoardMapper.java
  src/main/java/codestates/main007/board/BoardService.java
  src/main/java/codestates/main007/boardImage/BoardImage.java
  src/main/java/codestates/main007/boardImage/BoardImageRepository.java
  src/main/java/codestates/main007/boardImage/ImageHandler.java
Labels: back, feat

#84 Test 로그인 테스트 기능 구현
  client/src/App.js
  client/src/Routes/loginPage.js
  client/src/Routes/logoutPage.js
  client/src/atoms/loginTest.js
  client/src/components/Header.js
  client/src/components/MainPage/MainMapTest.js
Labels: front, feat

#90 Feat/withdrawal
  src/main/java/codestates/main007/boardImage/ImageHandler.java
  src/main/java/codestates/main007/member/Member.java
  src/main/java/codestates/main007/member/MemberController.java
  src/main/java/codestates/main007/member/MemberDto.java
  src/main/java/codestates/main007/member/MemberService.java
  src/main/resources/application.yml
Labels: back, feat

#89 Feat/mypage
  src/main/java/codestates/main007/board/BoardRepository.java
  src/main/java/codestates/main007/member/MemberController.java
  src/main/java/codestates/main007/member/MemberDto.java
  src/main/java/codestates/main007/member/MemberMapper.java
  src/main/java/codestates/main007/member/MemberService.java
  src/main/java/codestates/main007/service/EmailService.java
Labels: back, feat

#66 Feat: be-OAuth2
  build.gradle
  src/main/java/codestates/main007/auth/handler/MemberAuthenticationSuccessHandler.java
  src/main/java/codestates/main007/auth/handler/OAuthMemberAuthenticationSuccessHandler.java
  src/main/java/codestates/main007/auth/util/YeogiyoOAuth2Provider.java
  src/main/java/codestates/main007/config/SecurityConfiguration.java
  src/main/java/codestates/main007/member/MemberService.java
  src/main/resources/application.yml
  src/main/resources/templates/index.html
  src/main/resources/templates/my-page.html
  src/main/resources/templates/receive-token.html
Labels: back, feat

#95 메인페이지 카카오지도 기능 추가 밑 기타
  client/public/images/loading/train.png
  client/public/images/loading/기차.png
  client/public/images/loading/기차배경.png
  client/src/App.js
  client/src/Routes/editPasswordPage.js
  client/src/Routes/mainPage.js
  client/src/Routes/myPages/myCommentPage.js
  client/src/Routes/myPages/myLikePostPage.js
  client/src/Routes/myPages/myPostPage.js
  client/src/Routes/myPages/myProfilePage.js
  client/src/Routes/myPostPage.js
  client/src/atoms/dummyData.js
  client/src/atoms/mapImage.js
  client/src/components/Heart.js
  client/src/components/Loading.js
  client/src/components/MainPage/MainMapTest.js
  client/src/components/MainPage/Posts/Post.js
  client/src/components/MainPage/Posts/PostList.js
  client/src/components/MapItems/MapItem.js
  client/src/components/MapItems/MapItemDetail.js
  client/src/components/MapItems/MapItemTag.js
  client/src/components/MapItems/MapItemThumbnail.js
  client/src/components/TestInfinitiScroll.js
  client/src/components/homePage/HomeMap.js
  client/src/utils/timeFunc.js
  client/tailwind.config.js
Labels: style, front, feat

#96 Style/footer
  client/public/images/dot.png
  client/src/Routes/detailPage.js
  client/src/Routes/homePage.js
  client/src/Routes/mainPage.js
  client/src/Routes/postPage.js
  client/src/atoms/postInfo.js
  client/src/atoms/trainInfo.js
  client/src/components/PostPage/PostMap.js
  client/src/components/PostPage/PostTrainStationSelect.js
  client/src/components/TrainStationCard.js
  client/src/components/TrainStationSelect.js
  client/src/components/homePage/HomeIntroduce.js
  client/src/components/homePage/HomeMap.js
  client/src/components/homePage/HomeStamp.js
  client/src/components/modals/TrainStationModal.js
  client/src/components/modals/WriteModal.js
Labels: style, front

#100 test: 메인페이지 무한스크롤 기능 추가(테스트)
  client/src/Routes/mainPage.js
  client/src/Routes/myPages/myPostPage.js
  client/src/atoms/dummyData.js
  client/src/components/Loading.js
  client/src/components/MainPage/Posts/Post.js
  client/src/components/MainPage/Posts/TestPostList.js
  client/src/components/MainPage/TestMainMap.js
  client/src/components/PostPage/postRelatedAtmasTab.js
  client/src/components/TestInfinitiScroll.js
  client/src/index.css
Labels: style, front, feat

#101 home/post/detail/footer 디자인 수정 및 기능 추가 하였습니다
  client/public/images/기차역도장/김천구미역.png
  client/src/App.js
  client/src/Routes/detailPage.js
  client/src/Routes/homePage.js
  client/src/Routes/notFound.js
  client/src/Routes/postPage.js
  client/src/Routes/signoutPage.js
  client/src/Routes/signupPage.js
  client/src/atoms/postInfo.js
  client/src/atoms/trainInfo.js
  client/src/components/DetailPage/CommentEditor.js
  client/src/components/DetailPage/Comments/CommentList.js
  client/src/components/DetailPage/DetailHeader/DetailHeader.js
  client/src/components/DetailPage/DetailHeader/DetailStarScore.js
  client/src/components/DetailPage/DetailImageSlider.js
  client/src/components/DetailPage/DetailMap.js
  client/src/components/DetailPage/NeighborhoodPlace.js
  client/src/components/DetailPage/Review/Review.js
  client/src/components/Footer.js
  client/src/components/ImageUpload.js
  client/src/components/MainPage/Posts/PostStarScore.js
  client/src/components/OneLineComment.js
  client/src/components/OneLineInput.js
  client/src/components/PostPage/PostCategoriTabs.js
  client/src/components/PostPage/PostMap.js
  client/src/components/PostPage/PostRelatedTab.js
  client/src/components/PostPage/PostTrainStationSelect.js
  client/src/components/PostPage/postRelatedAtmasTab.js
  client/src/components/PostPage/postTestMap.js
  client/src/components/StarRating.js
  client/src/components/StarScore.js
  client/src/components/TrainStationCard.js
  client/src/components/homePage/HomeIntroduce.js
  client/src/components/homePage/HomeMap.js
  client/src/components/modals/WriteModal.js
  client/src/components/tag/ListTag.js
Labels: style, front

#102 마이페이지 - [내 여행 계획] 게시글 리스트 디자인 완료 하였습니다.
  client/src/App.js
  client/src/Routes/myPages/myTravelPage.js
  client/src/components/MainPage/Posts/PostStarScore.js
  client/src/components/OneStarScore.js
  client/src/components/PostPage/postRelatedPriceTab.js
  client/src/components/ViewLike/ViewDisLike.js
  client/src/components/ViewLike/ViewLike.js
  client/src/components/mytravel/ListItem/ListModal.js
  client/src/components/mytravel/ListItem/MyTravelHeader.js
  client/src/components/mytravel/ListItem/MyTravelPost.js
  client/src/components/mytravel/MyTravelList.js
  client/src/components/mytravel/MyTravelMap.js
  client/src/components/tag/viewTags/ViewTag.js
  client/src/components/tag/viewTags/ViewTagItem.js
Labels: style, front

#103 SNS 공유기능
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/Routes/detailPage.js
  client/src/Routes/postPage.js
  client/src/atoms/trainInfo.js
  client/src/components/DetailPage/DetailImageSlider.js
  client/src/components/DetailPage/DetailMap.js
  client/src/components/DetailPage/EveryShareButton.js
  client/src/components/DetailPage/KakaoShareButton.js
  client/src/components/ImageTest.js
  client/src/components/ImageUpload.js
  client/src/components/OneLineComment.js
  client/src/components/PostPage/PostCategoriTabs.js
  client/src/components/PostPage/PostMap.js
  client/src/components/PostPage/PostRelatedTab.js
  client/src/components/PostPage/PostTrainStationSelect.js
  client/src/components/PostPage/postRelatedAtmasTab.js
  client/src/components/TrainStationSelect.js
  client/src/components/homePage/HomeIntroduce.js
  client/src/components/homePage/HomeMap.js
  client/src/components/tag/ListTag.js
Labels: style, front

#104 마이페이지 디자인 변경 하였습니다.
  client/src/Routes/mainPage.js
  client/src/Routes/myPages/myLikePostPage.js
  client/src/Routes/myPages/myPostPage.js
  client/src/Routes/myPages/myTravelPage.js
  client/src/components/MainPage/Posts/PostList.js
  client/src/components/MyPageTab.js
  client/src/components/MyPostTab.js
  client/src/components/modals/ListModal.js
  client/src/components/mytravel/ListItem/ListModal.js
  client/src/components/mytravel/ListItem/MyTravelHeader.js
  client/src/components/mytravel/ListItem/MyTravelPost.js
  client/src/components/mytravel/MapItem/TravelMapItem.js
  client/src/components/mytravel/MyTravelList.js
  client/src/components/mytravel/MyTravelMap.js
Labels: style, front

#105 feat: 서버용 yml
  src/main/resources/application-server.yml
Labels: back

#92 feat: 이미지 용량 초과 시 리사이징
  src/main/java/codestates/main007/boardImage/ImageHandler.java
Labels: back, feat

#107 Feat/some change
  src/main/java/codestates/main007/board/Board.java
  src/main/java/codestates/main007/board/BoardController.java
  src/main/java/codestates/main007/board/BoardDto.java
  src/main/java/codestates/main007/board/BoardMapper.java
  src/main/java/codestates/main007/board/BoardRepository.java
  src/main/java/codestates/main007/board/BoardService.java
  src/main/java/codestates/main007/boardMember/BoardMemberService.java
  src/main/java/codestates/main007/comments/CommentDto.java
  src/main/java/codestates/main007/comments/CommentMapper.java
  src/main/java/codestates/main007/member/MemberDto.java
  src/main/java/codestates/main007/tag/TagDto.java
  src/main/java/codestates/main007/tag/TagService.java
Labels: back, feat

#108 마이페이지 - 내 여행 계획 페이지 기능 구현 완료
  client/src/App.js
  client/src/Routes/myPages/myLikePostPage.js
  client/src/Routes/myPages/myTravelPage.js
  client/src/components/modals/ListModal.js
  client/src/components/modals/MyTravelAddModal.js
  client/src/components/modals/MyTravelListModal.js
  client/src/components/mytravel/ListItem/MyTravelHeader.js
  client/src/components/mytravel/ListItem/MyTravelPost.js
  client/src/components/mytravel/MyTravelList.js
  client/src/components/mytravel/MyTravelMap.js
  client/src/index.css
Labels: style, front, feat

#109 디자인 수정 및 제작
  client/src/Routes/myPages/editPasswordPage.js
  client/src/Routes/myPages/myPostPage.js
  client/src/Routes/signoutPage.js
  client/src/components/Heart.js
  client/src/components/ImageTest.js
  client/src/components/ImageUpload.js
  client/src/components/MainPage/Posts/Post.js
  client/src/components/MainPage/Posts/PostList.js
  client/src/components/MainPage/Posts/TestPostList.js
  client/src/components/PostPage/PostTrainStationSelect.js
  client/src/components/TrainStationSelect.js
  client/src/components/editmyinfo/EditBtn.js
  client/src/components/editmyinfo/EditProfileImg.js
  client/src/components/editpassword/ConfirmPassword.js
  client/src/components/modals/TrainStationModal.js
  client/src/components/modals/WriteModal.js
  client/src/components/myprofile/infoeditbtn/InfoEditMenu.js
  client/src/components/mytravel/MyTravelDot.js
  client/src/components/mytravel/MyTravelDotCol.js
  client/src/components/mytravel/MyTravelList.js
  client/src/components/mytravel/MyTravelModal.js
Labels: style, front

#112 페이지네이션 구현, 스크롤바 디자인, 기타 버그 수정
  client/src/Routes/mainPage.js
  client/src/Routes/myPages/myCommentPage.js
  client/src/Routes/myPages/myPostPage.js
  client/src/components/MainPage/Posts/Post.js
  client/src/components/MainPage/Posts/PostList.js
  client/src/components/MainPage/TestMainMap.js
  client/src/components/modals/MyTravelListModal.js
  client/src/components/mycomment/MyCommentList.js
  client/src/components/mycomment/TestCommentPagination.js
  client/src/components/mytravel/ListItem/MyTravelHeader.js
  client/src/components/mytravel/MyTravelMap.js
  client/src/index.css
Labels: style, fix, front, feat

#110 Fix/be security
  src/main/java/codestates/main007/auth/filter/JwtAuthenticationFilter.java
  src/main/java/codestates/main007/auth/handler/MemberAuthenticationSuccessHandler.java
  src/main/java/codestates/main007/auth/handler/OAuthMemberAuthenticationSuccessHandler.java
  src/main/java/codestates/main007/auth/userDetails/UserDetailsServiceImpl.java
  src/main/java/codestates/main007/config/SecurityConfiguration.java
  src/main/java/codestates/main007/member/Member.java
Labels: fix, back

#113 내 댓글 페이지네이션 기능 구현 및 디자인
  client/src/Routes/myPages/myCommentPage.js
  client/src/components/mycomment/MyCommentItem.js
  client/src/components/mycomment/MyCommentList.js
  client/src/components/mycomment/MyCommentPagination.js
  client/src/index.css
Labels: style, front, feat

#115 메인페이지, 내 여행계획 수정하였습니다.
  client/src/Routes/myPages/myTravelPage.js
  client/src/components/MainPage/Posts/Post.js
  client/src/components/MapItems/MapItemDetail.js
  client/src/components/MapItems/MapItemTag.js
  client/src/components/MapItems/MapItemThumbnail.js
  client/src/components/mytravel/ListItem/MyTravelPost.js
  client/src/components/mytravel/MyTravelList.js
  client/src/components/mytravel/TestMyTravelModal.js
Labels: style, front, feat

#106 Feat/be scheduler구현
  src/main/java/codestates/main007/auth/handler/MemberAuthenticationSuccessHandler.java
  src/main/java/codestates/main007/auth/handler/OAuthMemberAuthenticationSuccessHandler.java
  src/main/java/codestates/main007/boardPlanner/BoardPlanner.java
  src/main/java/codestates/main007/boardPlanner/BoardPlannerController.java
  src/main/java/codestates/main007/boardPlanner/BoardPlannerDto.java
  src/main/java/codestates/main007/boardPlanner/BoardPlannerMapper.java
  src/main/java/codestates/main007/boardPlanner/BoardPlannerRepository.java
  src/main/java/codestates/main007/boardPlanner/BoardPlannerService.java
  src/main/java/codestates/main007/config/SecurityConfiguration.java
  src/main/java/codestates/main007/dto/MultiResponseDto.java
  src/main/java/codestates/main007/exception/ExceptionCode.java
  src/main/java/codestates/main007/member/Member.java
  src/main/java/codestates/main007/planner/Planner.java
  src/main/java/codestates/main007/planner/PlannerController.java
  src/main/java/codestates/main007/planner/PlannerDto.java
  src/main/java/codestates/main007/planner/PlannerMapper.java
  src/main/java/codestates/main007/planner/PlannerRepository.java
  src/main/java/codestates/main007/planner/PlannerService.java
Labels: back, feat

#117 [#97]: login page 수정
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Routes/callback.js
  client/src/Routes/initialPage.js
  client/src/Routes/loginPage.js
  client/src/Routes/logoutPage.js
  client/src/Routes/postPage.js
  client/src/Routes/signupPage.js
  client/src/atoms/loginTest.js
  client/src/components/Header.js
  client/src/components/ImageTest.js
  client/src/components/editmyinfo/EditProfileImg.js
  client/src/components/modals/ProfileModal.js
Labels: style, front

#118 구글 로그인 완료했습니다
  client/src/App.js
  client/src/Routes/callback.js
  client/src/Routes/postPage.js
  client/src/components/modals/ProfileModal.js
Labels: style, front

#119 메인페이지 - 게시글 데이터,카카오지도 데이터 API 연결
  client/public/index.html
  client/src/App.js
  client/src/Routes/mainPage.js
  client/src/Routes/myPages/myPostPage.js
  client/src/atoms/mainPageData.js
  client/src/atoms/tagsInfo.js
  client/src/components/Heart.js
  client/src/components/MainPage/MainMap.js
  client/src/components/MainPage/Posts/Post.js
  client/src/components/MainPage/Posts/SortDropdown.js
  client/src/components/MainPage/Posts/TestPostList.js
  client/src/components/MainPage/Posts/dummyPostList.js
  client/src/components/MainPage/TestMainMap.js
  client/src/components/MapItems/MapItem.js
  client/src/components/MapItems/MapItemDetail.js
  client/src/components/MapItems/MapItemTag.js
  client/src/components/MapItems/MapItemThumbnail.js
  client/src/components/mytravel/TestMyTravelModal.js
  client/src/index.css
  client/src/utils/useUserAction.js
  client/tailwind.config.js
Labels: style, front, feat

#121 Style/edit page
  client/src/Routes/callback.js
  client/src/Routes/detailPage.js
  client/src/Routes/loginPage.js
  client/src/Routes/postPage.js
  client/src/Routes/signupPage.js
  client/src/atoms/detailPageData.js
  client/src/atoms/postInfo.js
  client/src/components/DetailPage/CommentEditor.js
  client/src/components/DetailPage/Comments/Comment.js
  client/src/components/DetailPage/Comments/CommentList.js
  client/src/components/DetailPage/DetailHeader/DetailHeader.js
  client/src/components/DetailPage/DetailImageSlider.js
  client/src/components/DetailPage/DetailMap.js
  client/src/components/DetailPage/KakaoShareButton.js
  client/src/components/DetailPage/NeighborhoodPlace.js
  client/src/components/DetailPage/Review/Dislike.js
  client/src/components/DetailPage/Review/Like.js
  client/src/components/Header.js
  client/src/components/ImageUpload.js
  client/src/components/OneLineComment.js
  client/src/components/PostPage/PostMap.js
  client/src/components/editmyinfo/EditProfileImg.js
  client/src/components/homePage/HomeIntroduce.js
  client/src/components/modals/ProfileModal.js
  client/src/components/modals/WriteModal.js
Labels: style, front

#122 메인페이지 - 게시글 정보 통신
  client/src/Routes/mainPage.js
  client/src/atoms/mainPageData.js
  client/src/atoms/tagsInfo.js
  client/src/components/Heart.js
  client/src/components/MainPage/CategoryTab.js
  client/src/components/MainPage/MainMap.js
  client/src/components/MainPage/Posts/Post.js
  client/src/components/MainPage/Posts/TestPostList.js
  client/src/components/MainPage/TagTab.js
  client/src/components/MapItems/MapItem.js
  client/src/components/MapItems/MapItemDetail.js
  client/src/index.css
Labels: front, feat

#123 카테고리 단어 수정
  client/src/components/DetailPage/DetailHeader/DetailHeader.js
  client/src/components/DetailPage/KakaoShareButton.js
Labels: fix, front

#124 [#97]: post 페이지 swiper 스타일 빼고 완료
  client/public/images/oyster.png
  client/public/images/quote1.png
  client/public/images/quote2.png
  client/public/images/역이요노선/역이요_노선.png
  client/public/images/역이요노선/역이요_지도.png
  client/src/Routes/detailPage.js
  client/src/Routes/logoutPage.js
  client/src/components/DetailPage/CommentEditor.js
  client/src/components/DetailPage/DetailHeader/DetailHeader.js
  client/src/components/DetailPage/DetailHeader/DetailStarScore.js
  client/src/components/DetailPage/DetailHeader/detailHeart.js
  client/src/components/DetailPage/DetailMap.js
  client/src/components/DetailPage/NeighborhoodPlace.js
Labels: style, front

#125 메인페이지 - 필터 적용
  client/src/Routes/mainPage.js
  client/src/atoms/filter.js
  client/src/atoms/mainFilter.js
  client/src/atoms/mainPageData.js
  client/src/atoms/sort.js
  client/src/atoms/tagsInfo.js
  client/src/components/Heart.js
  client/src/components/MainPage/CategoryTab.js
  client/src/components/MainPage/Posts/Post.js
  client/src/components/MainPage/Posts/SortDropdown.js
  client/src/components/MainPage/Posts/TestPostList.js
  client/src/components/MainPage/TagTab.js
  client/src/components/TrainStationSelect.js
  client/tailwind.config.js
Labels: front, feat

#131 Refactor: planner responseBody 수정,boardPlanner중복방지
  src/main/java/codestates/main007/boardPlanner/BoardPlannerRepository.java
  src/main/java/codestates/main007/boardPlanner/BoardPlannerService.java
  src/main/java/codestates/main007/exception/ExceptionCode.java
  src/main/java/codestates/main007/planner/PlannerController.java
  src/main/java/codestates/main007/planner/PlannerMapper.java
  src/main/java/codestates/main007/planner/PlannerService.java
Labels: fix, back

#134 refactor: 토큰만료 에러메세지 수정
  src/main/java/codestates/main007/auth/jwt/JwtTokenizer.java
  src/main/java/codestates/main007/exception/ExceptionCode.java
Labels: fix, back

#137 마이페이지 - 내 여행 계획 통신 완료
  client/src/Routes/editPage.js
  client/src/Routes/mainPage.js
  client/src/Routes/myPages/myCommentPage.js
  client/src/Routes/myPages/myPostPage.js
  client/src/Routes/myPages/myTravelPage.js
  client/src/atoms/mypage/myTravelData.js
  client/src/components/MainPage/Posts/Post.js
  client/src/components/modals/MyTravelAddModal.js
  client/src/components/modals/MyTravelListModal.js
  client/src/components/mypost/mypostsitem/MyPost.js
  client/src/components/mytravel/ListItem/MyTravelHeader.js
  client/src/components/mytravel/ListItem/MyTravelPost.js
  client/src/components/mytravel/MyTravelList.js
  client/src/components/mytravel/MyTravelMap.js
  client/src/components/mytravel/TestMyTravelModal.js
  client/src/utils/timeFunc.js
Labels: front, feat

#138 디테일 페이지, 반응형 디자인
  client/package-lock.json
  client/package.json
  client/src/Routes/editPage.js
  client/src/Routes/forgotPassword.js
  client/src/Routes/homePage.js
  client/src/Routes/loginPage.js
  client/src/Routes/logoutPage.js
  client/src/Routes/postPage.js
  client/src/Routes/signoutPage.js
  client/src/Routes/signupPage.js
  client/src/atoms/postInfo.js
  client/src/components/DetailPage/Comments/Comment.js
  client/src/components/DetailPage/Comments/CommentList.js
  client/src/components/DetailPage/Complain.js
  client/src/components/DetailPage/DetailHeader/DetailHeader.js
  client/src/components/EditPage/EditCategoryTabs.js
  client/src/components/EditPage/EditImageUpload.js
  client/src/components/EditPage/EditListTag.js
  client/src/components/EditPage/EditMap.js
  client/src/components/EditPage/EditOneLineInput.js
  client/src/components/EditPage/EditRelatedAtmasTab.js
  client/src/components/EditPage/EditRelatedTab.js
  client/src/components/EditPage/EditStarRating.js
  client/src/components/EditPage/EditTrainStationSelect.js
  client/src/components/Footer.js
  client/src/components/ImageUpload.js
  client/src/components/PostPage/PostCategoryTabs.js
  client/src/components/PostPage/PostMap.js
  client/src/components/PostPage/PostOneLineInput.js
  client/src/components/PostPage/PostRelatedTab.js
  client/src/components/PostPage/PostTrainStationSelect.js
  client/src/components/PostPage/postRelatedAtmasTab.js
  client/src/components/StarRating.js
  client/src/components/TrainStationCard.js
  client/src/components/homePage/HomeIntroduce.js
  client/src/components/homePage/HomeMap.js
  client/src/components/modals/LoginDotModal.js
  client/src/components/modals/WriteModal.js
  client/src/components/myprofile/mystation/MyStation.js
  client/src/components/tag/ListTag.js
Labels: style, front

#135 Feat/be security refresh token
  src/main/java/codestates/main007/auth/filter/JwtAuthenticationFilter.java
  src/main/java/codestates/main007/auth/jwt/JwtTokenizer.java
  src/main/java/codestates/main007/auth/util/YeogiyoOAuth2Provider.java
  src/main/java/codestates/main007/config/SecurityConfiguration.java
  src/main/java/codestates/main007/member/Member.java
  src/main/java/codestates/main007/member/MemberController.java
  src/main/java/codestates/main007/member/MemberRepository.java
  src/main/java/codestates/main007/member/MemberService.java
Labels: back, feat

#139 Fix: BoardPlanner 10개제한추가
  src/main/java/codestates/main007/boardPlanner/BoardPlannerService.java
  src/main/java/codestates/main007/exception/ExceptionCode.java
Labels: fix, back

#140 Feat/home
  client/src/App.js
  client/src/Routes/callback.js
  client/src/Routes/detailPage.js
  client/src/Routes/loginPage.js
  client/src/Routes/logoutPage.js
  client/src/Routes/myPages/editMyInfoPage.js
  client/src/Routes/myPages/editPasswordPage.js
  client/src/Routes/myPages/myProfilePage.js
  client/src/Routes/postEditPage.js
  client/src/Routes/signoutPage.js
  client/src/atoms/loginTest.js
  client/src/components/DetailPage/CommentEditor.js
  client/src/components/DetailPage/Comments/Comment.js
  client/src/components/DetailPage/Comments/CommentList.js
  client/src/components/DetailPage/Complain.js
  client/src/components/DetailPage/DetailHeader/DetailHeader.js
  client/src/components/DetailPage/DetailHeader/DetailStarScore.js
  client/src/components/DetailPage/DetailImageSlider.js
  client/src/components/DetailPage/DetailMap.js
  client/src/components/DetailPage/EveryShareButton.js
  client/src/components/DetailPage/KakaoShareButton.js
  client/src/components/DetailPage/Review/Dislike.js
  client/src/components/DetailPage/Review/Like.js
  client/src/components/EditPage/EditImageUpload.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/ImageUpload.js
  client/src/components/LoginHeader.js
  client/src/components/MainPage/Posts/Post.js
  client/src/components/MyPageTab.js
  client/src/components/OneLineComment.js
  client/src/components/editmyinfo/EditNickname.js
  client/src/components/editmyinfo/EditProfileImg.js
  client/src/components/editpassword/ConfirmPassword.js
  client/src/components/editpassword/EditPasswordInput.js
  client/src/components/homePage/HomeIntroduce.js
  client/src/components/modals/ProfileModal.js
  client/src/components/mypost/mypostsitem/MyPost.js
  client/src/components/myprofile/infoeditbtn/InfoEditBtn.js
  client/src/components/myprofile/myinfo/MyEmail.js
  client/src/components/myprofile/myinfo/MyInfo.js
  client/src/components/myprofile/mystation/MyStation.js
Labels: style, front

#141 기타 디자인 변경 및 메인페이지 수정
  client/public/index.html
  client/src/App.js
  client/src/Routes/mainPage.js
  client/src/Routes/myPages/myCommentPage.js
  client/src/Routes/myPages/myPostPage.js
  client/src/Routes/myPages/myTravelPage.js
  client/src/atoms/mypage/myTravelData.js
  client/src/components/MainPage/MainMap.js
  client/src/components/MainPage/Posts/Post.js
  client/src/components/MainPage/Posts/PostList.js
  client/src/components/MainPage/Posts/SortDropdown.js
  client/src/components/MainPage/Posts/TestPostList.js
  client/src/components/MapItems/MapItemDetail.js
  client/src/components/MyPageTab.js
  client/src/components/TestInfinitiScroll.js
  client/src/components/homePage/HomeMap.js
  client/src/components/modals/MyTravelAddModal.js
  client/src/components/modals/MyTravelListModal.js
  client/src/components/modals/MyTravelModal.js
  client/src/components/mycomment/MyCommentItem.js
  client/src/components/mycomment/MyCommentList.js
  client/src/components/mypost/MyPostList.js
  client/src/components/mypost/MyPostMap.js
  client/src/components/mypost/mypostsitem/MyPost.js
  client/src/components/mypost/mypostsitem/MyPostList.js
  client/src/components/mytravel/ListItem/MyTravelHeader.js
  client/src/components/mytravel/ListItem/MyTravelPost.js
  client/src/components/mytravel/MyTravelDot.js
  client/src/components/mytravel/MyTravelList.js
  client/src/components/mytravel/MyTravelMap.js
  client/src/components/mytravel/MyTravelModal.js
  client/src/index.css
  client/src/utils/timeFunc.js
  client/tailwind.config.js
Labels: style, front, feat

#144 홈페이지 폰트 변경입니다.
  client/src/atoms/adminPage/data.js
  client/src/atoms/adminPage/report.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/homePage/HomeIntroduce.js
  client/src/components/mytravel/ListItem/MyTravelPost.js
  client/src/index.css
Labels: style, front

#145 Feat/home
  client/src/Routes/callback.js
  client/src/Routes/loginPage.js
  client/src/Routes/logoutPage.js
  client/src/atoms/loginData.js
  client/src/components/DetailPage/Comments/Comment.js
  client/src/components/DetailPage/Complain.js
  client/src/components/DetailPage/DetailHeader/DetailHeader.js
  client/src/components/DetailPage/DetailImageSlider.js
  client/src/components/DetailPage/DetailMap.js
  client/src/components/DetailPage/NeighborhoodPlace.js
  client/src/components/homePage/HomeMap.js
  client/src/components/modals/ProfileModal.js
  client/src/utils/timeFunc.js
Labels: front

#148 관리자 페이지 - 게시글 관리 추가
  client/src/App.js
  client/src/Routes/adminReportPage.js
  client/src/atoms/adminPage/adminTabState.js
  client/src/atoms/adminPage/issueData.js
  client/src/atoms/adminPage/report.js
  client/src/components/AdminIssue.js
  client/src/components/AdminTab.js
  client/src/components/Header.js
  client/src/components/LoginHeader.js
  client/src/components/adminReport/ReportHeader.js
  client/src/components/adminReport/ReportPost.js
  client/src/components/adminReport/ReportTable.js
  client/src/components/modals/ProfileModal.js
Labels: style, front, feat
