Repository codestates-seb/seb40_main_007, pull requests merged in 2022-12, with the labels that each got.

#152 Style/admin data
  client/src/App.js
  client/src/Routes/adminData.js
  client/src/Routes/logoutPage.js
  client/src/Routes/mainPage.js
  client/src/components/DetailPage/Comments/Comment.js
  client/src/components/DetailPage/Comments/CommentList.js
  client/src/components/DetailPage/Complain.js
  client/src/components/DetailPage/DetailImageSlider.js
  client/src/components/DetailPage/DetailMap.js
  client/src/components/DetailPage/KakaoShareButton.js
  client/src/components/EditPage/EditImageUpload.js
  client/src/components/Footer.js
  client/src/components/ImageUpload.js
  client/src/components/PostPage/PostMap.js
  client/src/components/adminData/StationData.js
  client/src/components/editmyinfo/EditNickname.js
  client/src/components/editmyinfo/EditProfileImg.js
  client/src/components/homePage/HomeMap.js
  client/src/setupProxy.js
Labels: style, front

#154 반응형 디자인 - 메인페이지, 내여행계획, 내게시글
  client/src/Routes/mainPage.js
  client/src/Routes/myPages/myCommentPage.js
  client/src/Routes/myPages/myPostPage.js
  client/src/components/MainPage/MainMap.js
  client/src/components/MainPage/Posts/PostList.js
  client/src/components/MainPage/Posts/PostStarScore.js
  client/src/components/MainPage/TagTab.js
  client/src/components/OneStarScore.js
  client/src/components/modals/MyTravelAddModal.js
  client/src/components/modals/MyTravelModal.js
  client/src/components/modals/MyTravelTimeModal.js
  client/src/components/modals/TrainStationModal.js
  client/src/components/mycomment/MyCommentItem.js
  client/src/components/mycomment/MyCommentList.js
  client/src/components/mypost/MyPostList.js
  client/src/components/mypost/MyPostMap.js
  client/src/components/mytravel/ListItem/MyTravelHeader.js
  client/src/components/mytravel/ListItem/MyTravelPost.js
  client/src/components/mytravel/MyTravelDot.js
  client/src/components/mytravel/MyTravelList.js
  client/src/components/mytravel/MyTravelMap.js
Labels: style, fix, front, feat

#156 로딩 변경
  client/public/images/loading/grassland.png
  client/public/images/loading/train.png
  client/public/images/loading/train2.png
  client/public/images/loading/train3.png
  client/public/images/loading/wind.png
  client/public/images/loading/기차.png
  client/public/images/loading/기차배경.png
  client/src/components/Loading.js
  client/src/components/MainPage/Posts/Post.js
  client/src/components/modals/MyTravelModal.js
  client/src/components/mytravel/ListItem/MyTravelPost.js
  client/src/components/mytravel/ListItem/MyTravelStarScore.js
  client/tailwind.config.js
Labels: style, front

#157 신고기능 추가
  client/src/App.js
  client/src/Routes/callback.js
  client/src/Routes/detailPage.js
  client/src/Routes/signupPage.js
  client/src/components/Alarm.js
  client/src/components/DetailPage/CommentEditor.js
  client/src/components/DetailPage/Comments/Comment.js
  client/src/components/DetailPage/DetailHeader/DetailHeader.js
  client/src/components/DetailPage/NeighborhoodPlace.js
  client/src/components/LoginHeader.js
  client/src/components/MainPage/Posts/Post.js
  client/src/components/modals/WriteModal.js
Labels: style, front, feat

#158 fix: 내 여행계획 버그 수정
  client/src/components/modals/MyTravelAddModal.js
  client/src/components/modals/MyTravelModal.js
  client/src/components/mytravel/MyTravelMap.js
Labels: fix, front

#159 Style/admin data
  client/src/App.js
  client/src/Routes/postEditPage.js
  client/src/components/DetailPage/CommentEditor.js
  client/src/components/DetailPage/Complain.js
  client/src/components/EditPage/EditImageUpload.js
  client/src/components/ImageUpload.js
  client/src/components/adminData/HighScoreData.js
  client/src/components/adminData/LowScoreData.js
  client/src/components/adminData/StationData.js
  client/src/components/adminData/WeekData.js
  client/src/components/editmyinfo/EditProfileImg.js
  client/src/components/myprofile/mystation/MyStation.js
Labels: style, front

#167 내 댓글 게시글 없는 상태 추가
  client/src/Routes/myPages/myCommentPage.js
  client/src/Routes/myPages/myPostPage.js
  client/src/components/modals/TrainStationModal.js
  client/src/components/mypost/MyPostList.js
  client/src/components/mypost/MyPostTab.js
  client/src/components/mytravel/MyTravelList.js
Labels: fix, front, feat

#168 FE-dev -> main merge
  client/src/Routes/myPages/myCommentPage.js
  client/src/Routes/myPages/myPostPage.js
  client/src/components/modals/TrainStationModal.js
  client/src/components/mypost/MyPostList.js
  client/src/components/mypost/MyPostTab.js
  client/src/components/mytravel/MyTravelList.js
Labels: front

#169 feat: 에러시 모달창 변경
  client/src/Routes/myPages/myTravelPage.js
  client/src/components/MyTravelTrainLoading.js
  client/src/components/mypost/MyPostList.js
  client/src/components/mytravel/MyTravelList.js
Labels: front

#171 FE-dev -> main 으로 merge
  client/src/Routes/myPages/myTravelPage.js
  client/src/components/MyTravelTrainLoading.js
  client/src/components/mypost/MyPostList.js
  client/src/components/mytravel/MyTravelList.js
Labels: front
